# Generated by Django 5.2.6 on 2025-09-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_deployedapp_id_alter_user_id_alter_user_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployedapp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('H', 'Hobby'), ('P', 'Pro')], default='H', max_length=1),
        ),
    ]
